version: '3'
services:
  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis:/data

  db:
    env_file: docker/.env-postgresql
    image: postgres:14
    restart: unless-stopped
    ports: # Added this section
      - "5433:5432" # Expose PostgreSQL port to host
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=superset
      - POSTGRES_USER=superset
      - POSTGRES_DB=superset

  superset:
    env_file: docker/.env-superset
    build: .
    image: superset-custom:latest # Added image name
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - superset-init  # Added superset-init dependency
    ports:
      - "8088:8088"
    volumes:
      - ./superset_home:/app/superset_home
      - ./docker/pythonpath_dev:/app/pythonpath
      - ./docker/init:/app/docker-init

  superset-init:
    build: .
    image: superset-custom-init:latest # Added image name
    depends_on:
      - db
      - redis
    env_file: docker/.env-superset
    volumes:
      - ./docker/init:/app/docker-init
      - ./docker/pythonpath_dev:/app/pythonpath # Added this line to mount the config
    command: >
      bash -c "/app/docker-init/superset-init.sh"

  superset-worker:
    env_file: docker/.env-superset
    build: .
    image: superset-custom-worker:latest # Added image name
    restart: unless-stopped
    depends_on:
      - db
      - redis
    volumes:
      - ./superset_home:/app/superset_home
      - ./docker/pythonpath_dev:/app/pythonpath
    command: >
      celery --app=superset.tasks.celery_app:app worker -Ofair -l INFO

volumes:
  redis:
  db_data: