version: "3"

services:
  namenode:
    build: . # Changed back from image: my-custom-hadoop:latest
    container_name: namenode_con
    hostname: namenode
    ports:
      - "9875:9870"  # Namenode web UI
      - "9000:9000"  # HDFS
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=hadoop-cluster
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "mkdir -p /hadoop/dfs/name &&
       # Only format if directory is empty
       [ -z \"$$(ls -A /hadoop/dfs/name)\" ] && echo Y | /opt/hadoop/bin/hdfs namenode -format || echo \"Namenode directory exists, skipping format\" &&
       /opt/hadoop/bin/hdfs --daemon start namenode &&
       tail -f /opt/hadoop/logs/*"
    networks:
      - hadoop_network

  datanode1:
    build: . # Changed back from image: my-custom-hadoop:latest
    container_name: datanode1_con
    hostname: datanode1
    ports:
      - "9864:9864"
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "mkdir -p /hadoop/dfs/data &&
       # Wait for namenode to be ready
       sleep 10 && 
       /opt/hadoop/bin/hdfs --daemon start datanode &&
       tail -f /opt/hadoop/logs/*"
    networks:
      - hadoop_network

  datanode2:
    build: . # Changed back from image: my-custom-hadoop:latest
    container_name: datanode2_con
    hostname: datanode2
    ports:
      - "9865:9864"
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "mkdir -p /hadoop/dfs/data &&
       # Wait for namenode to be ready
       sleep 15 &&
       /opt/hadoop/bin/hdfs --daemon start datanode &&
       tail -f /opt/hadoop/logs/*"
    networks:
      - hadoop_network

networks:
  hadoop_network:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2: